spring:
  application:
    name: CloudAlibaba
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      serverAddr: 127.0.0.1:8848 #?????????????????Nacos Server????
  config:
    import:
      - nacos:nacos-config-example.properties?refreshEnabled=true

server:
  port: 18084
management:
  endpoints:
    web:
      exposure:
        include: "*"